
Create TABLESPACE ALM_RPT
DATAFILE 'C:\App\oradata\ALM_RPT\DATAFILE\ALM_RPT.DBF'
SIZE 1m
AUTOEXTEND ON MAXSIZE UNLIMITED;

alter session set "_ORACLE_SCRIPT" = TRUE;

CREATE USER almrpt
IDENTIFIED BY almrpt
DEFAULT TABLESPACE ALM_RPT
QUOTA 20m on ALM_RPT;


GRANT ALL PRIVILEGES TO almrpt;


alter profile DEFAULT limit password_life_time UNLIMITED;


---------------SCRIPT TO CREATE RPT OBJECT-------------------------------------------------------
// if dblinkalm is existed and we need to create dblink from scratch, then we need to drop the dblinkalm.
DROP DATABASE LINK dblinkalm;

CREATE DATABASE LINK dblinkalm
CONNECT TO alm IDENTIFIED BY alm
USING 'ALM';    // ip/SID

CREATE SYNONYM alm_warehouse
FOR warehouse@dblinkalm;

CREATE SYNONYM alm_region
FOR region@dblinkalm;

CREATE SYNONYM alm_regionborder
FOR region_border@dblinkalm;

// To validate that dblinkalm has been created

select * from dba_db_links;

// To confirm that dblinkalm is working fine 
SELECT * FROM warehouse@dblinkalm;

// To confirm that SYNONYM is working fine:

select * from alm_warehouse;

DROP TABLE PREPAID_PAYG_REVENUE;

 CREATE TABLE PREPAID_PAYG_REVENUE 
   (	"ID" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"REVENUE_DATE" DATE NOT NULL ENABLE, 
	"CELL_ID" VARCHAR2(70 BYTE), 
	"CELL_NAME" VARCHAR2(100 BYTE), 
	"LAC" VARCHAR2(70 BYTE), 
	"GSM_CELL_ID" VARCHAR2(70 BYTE), 
	"NODE_ID" VARCHAR2(70 BYTE), 
	"SITE_ID" VARCHAR2(70 BYTE),
	"SITE_NAME" VARCHAR2(200 BYTE),
	"AREA_ID" VARCHAR2(70 BYTE), 
	"AREA_NAME" VARCHAR2(200 BYTE),
	"REGION_ID" VARCHAR2(100 BYTE),
	"REGION_NAME" VARCHAR2(200 BYTE),
	"VOICE_REVENUE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"SMS_REVENUE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DATA_REVENUE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"VAS_REVENUE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"TECH_2G" CHAR(1 BYTE) DEFAULT '0', 
	"TECH_3G" CHAR(1 BYTE) DEFAULT '0', 
	"TECH_4G" CHAR(1 BYTE) DEFAULT '0', 
	"TECH_5G" CHAR(1 BYTE) DEFAULT '0', 
	"COMMERCIAL_REGION" VARCHAR2(200 BYTE), 
	"SALES_TERRITORY" VARCHAR2(200 BYTE), 
	"LONGITUDE" VARCHAR2(100 BYTE), 
	"LATITUDE" VARCHAR2(100 BYTE), 
	"TECHNOLOGY_REGIONS" VARCHAR2(200 BYTE), 
	"KENYA_PROVINCES" VARCHAR2(200 BYTE), 
	"SITE_CLUSTER" VARCHAR2(200 BYTE), 
	"CLUSTER_TYPE" VARCHAR2(200 BYTE), 
	"RURAL_SITE_TYPE" VARCHAR2(200 BYTE), 
	"URBAN_RURAL" VARCHAR2(200 BYTE), 
	"METRO_CLUSTERS" VARCHAR2(200 BYTE), 
	"SUBLOCATIONS" VARCHAR2(200 BYTE), 
	"INDOOR_OUTDOOR" VARCHAR2(200 BYTE),
	 CONSTRAINT "PREPAID_PAYG_REVENUE_PK" PRIMARY KEY ("ID"));



TRUNCATE TABLE PREPAID_PAYG_REVENUE;

--alter SEQUENCE PREPAID_PAYG_REVENUE_SEQ restart start with 1;

CREATE SEQUENCE PREPAID_PAYG_REVENUE_SEQ MINVALUE 1 MAXVALUE 10000000000 INCREMENT BY 1 START WITH 571841 CACHE 20 NOORDER  NOCYCLE;

DROP SEQUENCE PREPAID_PAYG_REVENUE_SEQ;



